name: Contributor Graph

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Generate contributor graph
      uses: denolfe/contributor-graph@v1
      with:
        username: ${{ github.repository_owner }}
        token: ${{ secrets.GITHUB_TOKEN }}
        output_path: dist/github-contributor-graph.svg

    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add .
        git diff --staged --exit-code || git commit -m "Update README with the contributor graph"
        git push
